services:
  postgres:
    image: postgres:16
    container_name: postgres-dev
    restart: always
    env_file:
      - .env.dev
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
      - ../../../db/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - local_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2
    container_name: redis-track-dev
    ports:
      - "6379:6379"
    networks:
      - local_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.101.0
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ../../../observability/otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4318:4318"   # OTLP HTTP
      - "9888:9888"   # /metrics Prometheus scrape
    networks:
      - local_network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: prometheus-dev
    ports:
      - "9090:9090"
    volumes:
      - ../../../observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - local_network
    depends_on:
      - otel-collector

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ../../../observability/grafana/dashboards:/var/lib/grafana/dashboards
      - ../../../observability/grafana/provisioning:/etc/grafana/provisioning/dashboards
      - ../../../observability/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    networks:
      - local_network
    depends_on:
      - prometheus

  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: jaeger-dev
    restart: unless-stopped
    ports:
      - "16686:16686"   # UI Web
      - "9411:9411"     # Zipkin ingest
    networks:
      - local_network



networks:
  local_network:

volumes:
  postgres-data-dev:
  grafana-data:
